dependencies:
  - name: elasticsearch
    version: ^7.17.3
    repository: https://helm.elastic.co
    condition: elasticsearch.enabled
  - name: mongodb
    alias: mongodb-replicaset
    version: ^12.1.7
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb-replicaset.enabled
